sudo: required
language: node_js
node_js:
- '6'
- '7'
before_install:
  - export TZ=Africa/Nairobi
  - date
  - npm install -g node-gyp
  - cp $TRAVIS_BUILD_DIR/conf/config.example.json $TRAVIS_BUILD_DIR/conf/config.json
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
script:
- npm test
env:
  - CXX=g++-5
